apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service.default:8070/eureka/
  SPRING_CONFIG_IMPORT: optional:configserver:http://configserver-service.default:8071/
  SPRING_PROFILES_ACTIVE: prod
  SPRING_ZIPKIN_BASEURL: http://zipkin-service.default:9411/